# Generated by Django 5.1 on 2025-07-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessprofile",
            name="business_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="businessprofile",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
