# Generated by Django 5.2.3 on 2025-07-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="location",
            field=models.CharField(
                blank=True, help_text="Business address or location", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="phone",
            field=models.CharField(
                blank=True, help_text="Contact phone number", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="timing",
            field=models.CharField(
                blank=True,
                help_text="Business hours (e.g., 9:00 AM - 8:00 PM)",
                max_length=100,
            ),
        ),
    ]
