# Generated by Django 5.2.3 on 2025-07-20 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_add_poster_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessprofile",
            name="image_url",
            field=models.URLField(
                blank=True, help_text="Cloudinary URL for business logo"
            ),
        ),
        migrations.CreateModel(
            name="UserHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("poster_generation", "Poster Generation"),
                            ("text_generation", "Text Generation"),
                            ("logo_upload", "Logo Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "input_data",
                    models.JSONField(help_text="Original input data from user"),
                ),
                (
                    "output_data",
                    models.TextField(help_text="Generated content or Cloudinary URL"),
                ),
                (
                    "prompt_used",
                    models.TextField(blank=True, help_text="Final prompt sent to AI"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User History",
                "verbose_name_plural": "User Histories",
                "ordering": ["-created_at"],
            },
        ),
    ]
